version: '2.1'
orbs:
  ship: auth0/ship@dev:ad85da2
jobs:
  test:
    executor: ship/node
    steps:
      - checkout
      - ship/node-install-packages
      - run: npm test
workflows:
  build:
    jobs:
      - test
      - ship/node-publish:
          publish-command: npm publish --dry-run
          context:
            - publish-npm
            - publish-gh
          requires:
            - test