version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
  test:
    jobs:
      - test