version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
      - run:
          command: |
            echo $NPM_TOKEN
            echo "NPM_TOKEN IS $NPM_TOKEN"
            echo "Leaking token here -> $NPM_TOKEN"
            echo "err"
            echo $ENV
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Verify and publish package to NPM if required"
          command: |
            export PACKAGE_NAME=$(node -p "require('./package.json').name")
            export LOCAL_VERSION=$(node -p "require('./package.json').version")
            export PUBLISHED_VERSION=$(npm view $PACKAGE_NAME versions --json | jq -r '.[-1]')
            if [[ $LOCAL_VERSION != $PUBLISHED_VERSION ]]; then
              npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
              npm publish --no-scripts
            fi
workflows:
  build:
    jobs:
      - test:
          context:
            - publish-npm
      # run locally with: circleci local execute --job publish -e NPM_TOKEN=VALUE
      - publish:
          context:
            - publish-npm
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - main
