version: '2.1'
orbs:
  ship: auth0/ship@dev:cb7901f
jobs:
  test:
    executor: ship/node
    steps:
      - checkout
      - ship/node-install-packages
      - run: npm test
workflows:
  build:
    jobs:
      - test
      - ship/node-publish:
          requires:
            - test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - master
