version: '2.1'
orbs:
  node-publisher: lbalmaceda/node-publisher@dev:d1b8cd7
workflows:
  build:
    jobs:
      - node-publisher/test
      - node-publisher/publish:
          context:
            - publish-npm
          requires:
            - node-publisher/test
          filters:
            branches:
              only:
                - master
