version: '2.1'
orbs:
  ship: lbalmaceda/node-publisher@dev:e838acf
jobs:
  test:
    executor: ship/node
    steps:
      - checkout
      - ship/node-install-packages
      - run: npm test
workflows:
  build:
    jobs:
      - test
      - ship/node-publish:
          context:
            - publish-npm
          requires:
            - test
          filters:
            branches:
              only:
                - master
