version: '2.1'
orbs:
  ship: lbalmaceda/node-publisher@dev:1eaf527
jobs:
  gh-release:
    executor: ship/node
    steps:
      - checkout
      - ship/github-release
workflows:
  build:
    jobs:
      - gh-release
      # - ship/test
      # - ship/publish:
      #     context:
      #       - publish-npm
      #     requires:
      #       - node-publisher/test
      #     filters:
      #       branches:
      #         only:
      #           - master
